# See https://pre-commit.com/ for usage and config
default_language_version:
  python: python3.7
repos:
- repo: local
  hooks:
  - id: formatting
    name: formatting
    stages: [commit]
    language: system
    entry: bash -c "export PYTHONPATH=src; poetry run python src/delfino/main.py format"
    pass_filenames: false
